apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    # This label is the trigger. Istio will automatically inject 
    # Envoy proxies into any new pod created in this namespace.
    istio-injection: enabled