alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: "admin" # only for demo
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: "2d" 
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi