fullnameOverride: "vm" # prevent long DNS name

# Disable optional features
alertmanager:
  enabled: false
vmalert:
  enabled: false

# Resource Tuning
vmsingle:
  spec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 350Mi

grafana:
  enabled: true
  adminPassword: "admin" # only for demo
  service:
    type: ClusterIP

# To prevent Race Condition
victoria-metrics-operator:
  admissionWebhooks:
    enabled: false

vmagent:
  enabled: true
  spec:
    # VMAgent microservices discovery
    inlineScrapeConfig: |
      - job_name: 'boutique-microservices'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # targeting pods that are permitted to be scraped
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          # get app name to be used as label
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace