apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/6ill/cloud-microservices-demo/kustomize/base

patches:
- path: ./patches/Deployment.adservice.yaml
- path: ./patches/Deployment.cartservice.yaml
- target:
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
images:
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
  newName: ghcr.io/6ill/adservice
  newTag: 217ccbeb0084c90e22f5208ea6754383c76bee35
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
  newName: ghcr.io/6ill/cartservice
  newTag: a8827a17d19bed0bb9c91b27465daa8ed80a2115
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
  newName: ghcr.io/6ill/checkoutservice
  newTag: 0042cdfb76e8e30b4425f7c6f577e6dc693f200d
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
  newName: ghcr.io/6ill/recommendationservice
  newTag: 217ccbeb0084c90e22f5208ea6754383c76bee35

commonAnnotations:
  prometheus.io/scrape: "true"