apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/6ill/cloud-microservices-demo/kustomize/base
- patches/Ingress.frontend.yaml






patches:
- path: ./patches/Deployment.adservice.yaml
- path: ./patches/Deployment.cartservice.yaml
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  target:
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: ENABLE_TRACING
                value: "1"
              - name: OTEL_SERVICE_NAME
                value: "frontend"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.monitoring.svc.cluster.local:4317"
              - name: COLLECTOR_SERVICE_ADDR
                value: "alloy.monitoring.svc.cluster.local:4317"
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: checkoutservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: ENABLE_TRACING
                value: "1"
              - name: OTEL_SERVICE_NAME
                value: "checkoutservice"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.monitoring.svc.cluster.local:4317"
              - name: COLLECTOR_SERVICE_ADDR
                value: "alloy.monitoring.svc.cluster.local:4317"
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: currencyservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: ENABLE_TRACING
                value: "1"
              - name: OTEL_SERVICE_NAME
                value: "currencyservice"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.monitoring.svc.cluster.local:4317"
              - name: COLLECTOR_SERVICE_ADDR
                value: "alloy.monitoring.svc.cluster.local:4317"
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: emailservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: ENABLE_TRACING
                value: "1"
              - name: OTEL_SERVICE_NAME
                value: "emailservice"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.monitoring.svc.cluster.local:4317"
              - name: COLLECTOR_SERVICE_ADDR
                value: "alloy.monitoring.svc.cluster.local:4317"
- patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: paymentservice\nspec:\n
    \ template:\n    spec:\n      containers:\n        - name: server\n          env:\n
    \         - name: ENABLE_TRACING\n            value: \"1\"\n          - name:
    OTEL_SERVICE_NAME\n            value: \"paymentservice\"\n          - name: OTEL_EXPORTER_OTLP_ENDPOINT\n
    \           value: \"http://alloy.monitoring.svc.cluster.local:4317\"\n          -
    name: COLLECTOR_SERVICE_ADDR\n            value: \"alloy.monitoring.svc.cluster.local:4317\"
    \     "
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: productcatalogservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: ENABLE_TRACING
                value: "1"
              - name: OTEL_SERVICE_NAME
                value: "productcatalogservice"
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.monitoring.svc.cluster.local:4317"
              - name: COLLECTOR_SERVICE_ADDR
                value: "alloy.monitoring.svc.cluster.local:4317"
- patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: recommendationservice\nspec:\n
    \ template:\n    spec:\n      containers:\n        - name: server\n          env:\n
    \         - name: ENABLE_TRACING\n            value: \"1\"\n          - name:
    OTEL_SERVICE_NAME\n            value: \"recommendationservice\"\n          - name:
    OTEL_EXPORTER_OTLP_ENDPOINT\n            value: \"http://alloy.monitoring.svc.cluster.local:4317\"\n
    \         - name: COLLECTOR_SERVICE_ADDR\n            value: \"alloy.monitoring.svc.cluster.local:4317\"
    \ "
    
images:
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
  newName: ghcr.io/6ill/adservice
  newTag: 217ccbeb0084c90e22f5208ea6754383c76bee35
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
  newName: ghcr.io/6ill/cartservice
  newTag: a8827a17d19bed0bb9c91b27465daa8ed80a2115
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
  newName: ghcr.io/6ill/checkoutservice
  newTag: cb294c9a536ce4e98a8b20c7f1088f1bbb235a2a
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
  newName: ghcr.io/6ill/frontend
  newTag: 174f22396a50dd48daebd319d6e8482df940cbc8
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
  newName: ghcr.io/6ill/recommendationservice
  newTag: 217ccbeb0084c90e22f5208ea6754383c76bee35

commonAnnotations:
  prometheus.io/scrape: "true"
